services:
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    container_name: nginx-proxy-manager
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ${PWD}/nginx/data:/data
      - ${PWD}/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - proxy
networks:
  proxy:
    driver: bridge
